using SolarPanel.Data;
using SolarPanel.Logic.Utilities;
using SolarPanel.Types;

namespace SolarPanel.Application
{

    /// <summary>
    /// Provides calculation capabilities for computing solar panel profits
    /// </summary>
    internal class CalculationEngine
    {
        /// <summary>
        /// Computes the metrics for the specified configuration
        /// </summary>
        /// <param name="house">The house</param>
        /// <param name="panel">The type of panel fitted</param>
        /// <param name="tariff">The tariff to use</param>
        /// <param name="installer">The installer to use</param>
        /// <param name="numberOfYears">The number of years to compute the economics over</param>
        /// <returns>The economics</returns>
        public static SolarPanelEconomics Compute(House house, Panel panel, Tariff tariff, Installer installer, int numberOfYears)
        {
            // Compute the number of panels that can be fitted to the house
            int numberOfPanels = HouseUtilities.MaxNumberOfPanels(house, panel);

            var fitted = new HouseWithPanel(house, panel, numberOfPanels);

            // Compute the purchase price of the panels
            float panelPurchaseCost = numberOfPanels * panel.Cost;
            // Compute the installation cost of the panels
            float installationCost = installer.CallOutCost + (numberOfPanels * installer.CostPerPanel);

            // Compute the total cost of installation and purchase
            float totalCost = panelPurchaseCost + installationCost;

            // Now project into the future looking to see how much electricity is generated by 
            // this house over the coming years
            DateTime now = DateTime.Now;

            float totalMoneyGenerated = 0f;
            float totalMoneySavedOnBills = 0f;
            float totalMoneyMadeInProfit = 0f;

            DateTime? breakEvenDate = null;

            foreach (var day in DateProvider.Instance.GetDays(now, DateProvider.Instance.ComputeYears(now, numberOfYears)))
            {
                // Get the average number of usable daylight hours for today 
                float usableDaylightHours = DaylightProvider.Instance.GetUsableDaylight(day.Month);

                float kiloWatts = HouseUtilities.PowerGeneratedForHouse(fitted, usableDaylightHours) / 1000f;

                float dailyKiloWattsHouseConsumption = house.DaylightElectricityConsumption / 1000f;

                // Work out how much power is consumed by the house
                float leftOverKiloWatts = kiloWatts - dailyKiloWattsHouseConsumption;

                float kiloWattHoursSentToGrid;
                float kiloWattHoursConsumedByHouse;

                if (leftOverKiloWatts > 0f)
                {
                    // We have some left over to send to the grid
                    kiloWattHoursSentToGrid = leftOverKiloWatts;
                    kiloWattHoursConsumedByHouse = dailyKiloWattsHouseConsumption;
                }
                else
                {
                    // It's all consumed by the house
                    kiloWattHoursSentToGrid = 0;
                    kiloWattHoursConsumedByHouse = kiloWatts;
                }

                // Use the house energy tariff to compute how much was saved from the electricity bill
                float dailySavingOnElectricityBillPounds = house.ElectricityCost * kiloWattHoursConsumedByHouse;

                // Compute the tariff cost
                float dayTariffPencePerKilowattHour = day <= tariff.Expiry ? tariff.Price : tariff.ExpiredPrice;
                float dayTariffPoundPerKilowattHour = dayTariffPencePerKilowattHour / 100f;

                // Use the feed in tariff to compute how much is paid by the electicity supplies
                float dailyProfit = kiloWattHoursSentToGrid * dayTariffPoundPerKilowattHour;

                // Increment the total money for today
                totalMoneyGenerated += dailySavingOnElectricityBillPounds + dailyProfit;
                totalMoneySavedOnBills += dailySavingOnElectricityBillPounds;
                totalMoneyMadeInProfit += dailyProfit;

                if (breakEvenDate.HasValue == false && totalMoneyGenerated > totalCost)
                {
                    // We've broken even!
                    breakEvenDate = day;
                }
            }

            float totalProfitOverTimePeriod = totalMoneyGenerated - totalCost;

            return new SolarPanelEconomics(installationCost,
                                         panelPurchaseCost,
                                         numberOfPanels,
                                         totalCost,
                                         breakEvenDate,
                                         breakEvenDate - now,
                                         totalProfitOverTimePeriod,
                                         totalMoneySavedOnBills,
                                         totalMoneyMadeInProfit);
        }
    }
}
